/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_datakernel_aio_nativeio_AioNative */

#ifndef _Included_io_datakernel_aio_nativeio_AioNative
#define _Included_io_datakernel_aio_nativeio_AioNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_datakernel_aio_nativeio_AioNative
 * Method:    io_setup
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_datakernel_aio_nativeio_AioNative_io_1setup
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_datakernel_aio_nativeio_AioNative
 * Method:    io_submit
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_io_datakernel_aio_nativeio_AioNative_io_1submit
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     io_datakernel_aio_nativeio_AioNative
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_datakernel_aio_nativeio_AioNative_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_datakernel_aio_nativeio_AioNative
 * Method:    io_getevents
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_io_datakernel_aio_nativeio_AioNative_io_1getevents
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     io_datakernel_aio_nativeio_AioNative
 * Method:    cancel
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_datakernel_aio_nativeio_AioNative_cancel
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
