/**
 * This class is generated by jOOQ
 */
package io.datakernel.aggregation_db.sql;


import io.datakernel.aggregation_db.sql.tables.AggregationDbChunk;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table aggregation_db_chunk
	 */
	public static final AggregationDbChunk AGGREGATION_DB_CHUNK = io.datakernel.aggregation_db.sql.tables.AggregationDbChunk.AGGREGATION_DB_CHUNK;
}
