/*
 * Copyright (C) 2015 SoftIndex LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This class is generated by jOOQ
 */
package io.datakernel.aggregation_db.sql;


import io.datakernel.aggregation_db.sql.tables.AggregationDbChunk;
import io.datakernel.aggregation_db.sql.tables.AggregationDbLog;
import io.datakernel.aggregation_db.sql.tables.AggregationDbRevision;
import io.datakernel.aggregation_db.sql.tables.AggregationDbStructure;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table aggregation_db_chunk
	 */
	public static final AggregationDbChunk AGGREGATION_DB_CHUNK = io.datakernel.aggregation_db.sql.tables.AggregationDbChunk.AGGREGATION_DB_CHUNK;

	/**
	 * The table aggregation_db_log
	 */
	public static final AggregationDbLog AGGREGATION_DB_LOG = io.datakernel.aggregation_db.sql.tables.AggregationDbLog.AGGREGATION_DB_LOG;

	/**
	 * The table aggregation_db_revision
	 */
	public static final AggregationDbRevision AGGREGATION_DB_REVISION = io.datakernel.aggregation_db.sql.tables.AggregationDbRevision.AGGREGATION_DB_REVISION;

	/**
	 * The table aggregation_db_structure
	 */
	public static final AggregationDbStructure AGGREGATION_DB_STRUCTURE = io.datakernel.aggregation_db.sql.tables.AggregationDbStructure.AGGREGATION_DB_STRUCTURE;
}
