/*
 * Copyright (C) 2015 SoftIndex LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This class is generated by jOOQ
 */
package io.datakernel.cube.sql;

import io.datakernel.cube.sql.tables.AggregationChunk;
import io.datakernel.cube.sql.tables.AggregationLog;
import io.datakernel.cube.sql.tables.AggregationRevision;
import io.datakernel.cube.sql.tables.AggregationStructure;

import javax.annotation.Generated;

/**
 * Convenience access to all tables in
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.6.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

	/**
	 * The table aggregation_chunk
	 */
	public static final AggregationChunk AGGREGATION_CHUNK = AggregationChunk.AGGREGATION_CHUNK;

	/**
	 * The table aggregation_log
	 */
	public static final AggregationLog AGGREGATION_LOG = AggregationLog.AGGREGATION_LOG;

	/**
	 * The table aggregation_revision
	 */
	public static final AggregationRevision AGGREGATION_REVISION = AggregationRevision.AGGREGATION_REVISION;

	/**
	 * The table aggregation_structure
	 */
	public static final AggregationStructure AGGREGATION_STRUCTURE = AggregationStructure.AGGREGATION_STRUCTURE;
}
