/**
 * This class is generated by jOOQ
 */
package io.datakernel.aggregation.sql.tables;

import io.datakernel.aggregation.sql.DefaultSchema;
import io.datakernel.aggregation.sql.Keys;
import io.datakernel.aggregation.sql.tables.records.AggregationDbChunkRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregationDbChunk extends TableImpl<AggregationDbChunkRecord> {

	private static final long serialVersionUID = 870790371;

	/**
	 * The reference instance of <code>aggregation_db_chunk</code>
	 */
	public static final AggregationDbChunk AGGREGATION_DB_CHUNK = new AggregationDbChunk();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AggregationDbChunkRecord> getRecordType() {
		return AggregationDbChunkRecord.class;
	}

	/**
	 * The column <code>aggregation_db_chunk.id</code>.
	 */
	public final TableField<AggregationDbChunkRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>aggregation_db_chunk.created</code>.
	 */
	public final TableField<AggregationDbChunkRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>aggregation_db_chunk.aggregation_id</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> AGGREGATION_ID = createField("aggregation_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>aggregation_db_chunk.revision_id</code>.
	 */
	public final TableField<AggregationDbChunkRecord, Integer> REVISION_ID = createField("revision_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>aggregation_db_chunk.count</code>.
	 */
	public final TableField<AggregationDbChunkRecord, Integer> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>aggregation_db_chunk.consolidated_revision_id</code>.
	 */
	public final TableField<AggregationDbChunkRecord, Integer> CONSOLIDATED_REVISION_ID = createField("consolidated_revision_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>aggregation_db_chunk.consolidation_started</code>.
	 */
	public final TableField<AggregationDbChunkRecord, Timestamp> CONSOLIDATION_STARTED = createField("consolidation_started", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>aggregation_db_chunk.consolidation_completed</code>.
	 */
	public final TableField<AggregationDbChunkRecord, Timestamp> CONSOLIDATION_COMPLETED = createField("consolidation_completed", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>aggregation_db_chunk.process_id</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> PROCESS_ID = createField("process_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>aggregation_db_chunk.keys</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> KEYS = createField("keys", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>aggregation_db_chunk.fields</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> FIELDS = createField("fields", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>aggregation_db_chunk.d1_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D1_MIN = createField("d1_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d1_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D1_MAX = createField("d1_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d2_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D2_MIN = createField("d2_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d2_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D2_MAX = createField("d2_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d3_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D3_MIN = createField("d3_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d3_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D3_MAX = createField("d3_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d4_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D4_MIN = createField("d4_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d4_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D4_MAX = createField("d4_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d5_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D5_MIN = createField("d5_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d5_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D5_MAX = createField("d5_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d6_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D6_MIN = createField("d6_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d6_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D6_MAX = createField("d6_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d7_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D7_MIN = createField("d7_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d7_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D7_MAX = createField("d7_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d8_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D8_MIN = createField("d8_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d8_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D8_MAX = createField("d8_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d9_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D9_MIN = createField("d9_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d9_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D9_MAX = createField("d9_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d10_min</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D10_MIN = createField("d10_min", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>aggregation_db_chunk.d10_max</code>.
	 */
	public final TableField<AggregationDbChunkRecord, String> D10_MAX = createField("d10_max", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>aggregation_db_chunk</code> table reference
	 */
	public AggregationDbChunk() {
		this("aggregation_db_chunk", null);
	}

	/**
	 * Create an aliased <code>aggregation_db_chunk</code> table reference
	 */
	public AggregationDbChunk(String alias) {
		this(alias, AGGREGATION_DB_CHUNK);
	}

	private AggregationDbChunk(String alias, Table<AggregationDbChunkRecord> aliased) {
		this(alias, aliased, null);
	}

	private AggregationDbChunk(String alias, Table<AggregationDbChunkRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AggregationDbChunkRecord, Long> getIdentity() {
		return Keys.IDENTITY_AGGREGATION_DB_CHUNK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AggregationDbChunkRecord> getPrimaryKey() {
		return Keys.KEY_AGGREGATION_DB_CHUNK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AggregationDbChunkRecord>> getKeys() {
		return Arrays.<UniqueKey<AggregationDbChunkRecord>>asList(Keys.KEY_AGGREGATION_DB_CHUNK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbChunk as(String alias) {
		return new AggregationDbChunk(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AggregationDbChunk rename(String name) {
		return new AggregationDbChunk(name, null);
	}
}
