CREATE TABLE `aggregation_db_chunk_backup` (
  `backup_revision_id` int(11) NOT NULL,
  `id` bigint(20) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `aggregation_id` varchar(100) NOT NULL DEFAULT '',
  `revision_id` int(11) NOT NULL,
  `count` int(11) NOT NULL,
  `consolidated_revision_id` int(11) DEFAULT NULL,
  `consolidation_started` timestamp NULL DEFAULT NULL,
  `consolidation_completed` timestamp NULL DEFAULT NULL,
  `keys` varchar(1000) NOT NULL DEFAULT '',
  `fields` varchar(1000) NOT NULL DEFAULT '',
  `d1_min` text,
  `d1_max` text,
  `d2_min` text,
  `d2_max` text,
  `d3_min` text,
  `d3_max` text,
  `d4_min` text,
  `d4_max` text,
  `d5_min` text,
  `d5_max` text,
  `d6_min` text,
  `d6_max` text,
  `d7_min` text,
  `d7_max` text,
  `d8_min` text,
  `d8_max` text,
  `d9_min` text,
  `d9_max` text,
  `d10_min` text,
  `d10_max` text,
  `d11_min` text,
  `d11_max` text,
  `d12_min` text,
  `d12_max` text,
  `d13_min` text,
  `d13_max` text,
  `d14_min` text,
  `d14_max` text,
  `d15_min` text,
  `d15_max` text,
  `d16_min` text,
  `d16_max` text,
  `d17_min` text,
  `d17_max` text,
  `d18_min` text,
  `d18_max` text,
  `d19_min` text,
  `d19_max` text,
  `d20_min` text,
  `d20_max` text,
  `d21_min` text,
  `d21_max` text,
  `d22_min` text,
  `d22_max` text,
  `d23_min` text,
  `d23_max` text,
  `d24_min` text,
  `d24_max` text,
  `d25_min` text,
  `d25_max` text,
  `d26_min` text,
  `d26_max` text,
  `d27_min` text,
  `d27_max` text,
  `d28_min` text,
  `d28_max` text,
  `d29_min` text,
  `d29_max` text,
  `d30_min` text,
  `d30_max` text,
  `d31_min` text,
  `d31_max` text,
  `d32_min` text,
  `d32_max` text,
  `d33_min` text,
  `d33_max` text,
  `d34_min` text,
  `d34_max` text,
  `d35_min` text,
  `d35_max` text,
  `d36_min` text,
  `d36_max` text,
  `d37_min` text,
  `d37_max` text,
  `d38_min` text,
  `d38_max` text,
  `d39_min` text,
  `d39_max` text,
  `d40_min` text,
  `d40_max` text,
  PRIMARY KEY (`backup_revision_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;