CREATE TABLE `aggregation_db_chunk_backup` (
  `backup_revision_id` int(11) NOT NULL,
  `id` bigint(20) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `aggregation_id` varchar(100) NOT NULL DEFAULT '',
  `revision_id` int(11) NOT NULL,
  `count` int(11) NOT NULL,
  `consolidated_revision_id` int(11) DEFAULT NULL,
  `consolidation_started` timestamp NULL DEFAULT NULL,
  `consolidation_completed` timestamp NULL DEFAULT NULL,
  `keys` varchar(1000) NOT NULL DEFAULT '',
  `fields` varchar(1000) NOT NULL DEFAULT '',
  `d1_min` text,
  `d1_max` text,
  `d2_min` text,
  `d2_max` text,
  `d3_min` text,
  `d3_max` text,
  `d4_min` text,
  `d4_max` text,
  `d5_min` text,
  `d5_max` text,
  `d6_min` text,
  `d6_max` text,
  `d7_min` text,
  `d7_max` text,
  `d8_min` text,
  `d8_max` text,
  `d9_min` text,
  `d9_max` text,
  `d10_min` text,
  `d10_max` text,
  PRIMARY KEY (`backup_revision_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;