/*
 * Copyright (C) 2015 SoftIndex LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This class is generated by jOOQ
 */
package io.datakernel.cube.sql.tables.records;


import io.datakernel.cube.sql.tables.AggregationDbLog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregationDbLogRecord extends UpdatableRecordImpl<AggregationDbLogRecord> implements Record6<Integer, String, String, String, Integer, Long> {

	private static final long serialVersionUID = 885476737;

	/**
	 * Setter for <code>aggregation_db_log.revision_id</code>.
	 */
	public void setRevisionId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>aggregation_db_log.revision_id</code>.
	 */
	public Integer getRevisionId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>aggregation_db_log.log</code>.
	 */
	public void setLog(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>aggregation_db_log.log</code>.
	 */
	public String getLog() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>aggregation_db_log.partition</code>.
	 */
	public void setPartition(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>aggregation_db_log.partition</code>.
	 */
	public String getPartition() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>aggregation_db_log.file</code>.
	 */
	public void setFile(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>aggregation_db_log.file</code>.
	 */
	public String getFile() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>aggregation_db_log.file_index</code>.
	 */
	public void setFileIndex(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>aggregation_db_log.file_index</code>.
	 */
	public Integer getFileIndex() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>aggregation_db_log.position</code>.
	 */
	public void setPosition(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>aggregation_db_log.position</code>.
	 */
	public Long getPosition() {
		return (Long) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, Integer, Long> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, Integer, Long> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AggregationDbLog.AGGREGATION_DB_LOG.REVISION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AggregationDbLog.AGGREGATION_DB_LOG.LOG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AggregationDbLog.AGGREGATION_DB_LOG.PARTITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return AggregationDbLog.AGGREGATION_DB_LOG.FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return AggregationDbLog.AGGREGATION_DB_LOG.FILE_INDEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return AggregationDbLog.AGGREGATION_DB_LOG.POSITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getRevisionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLog();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPartition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getFileIndex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getPosition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbLogRecord value1(Integer value) {
		setRevisionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbLogRecord value2(String value) {
		setLog(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbLogRecord value3(String value) {
		setPartition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbLogRecord value4(String value) {
		setFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbLogRecord value5(Integer value) {
		setFileIndex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbLogRecord value6(Long value) {
		setPosition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbLogRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Long value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AggregationDbLogRecord
	 */
	public AggregationDbLogRecord() {
		super(AggregationDbLog.AGGREGATION_DB_LOG);
	}

	/**
	 * Create a detached, initialised AggregationDbLogRecord
	 */
	public AggregationDbLogRecord(Integer revisionId, String log, String partition, String file, Integer fileIndex, Long position) {
		super(AggregationDbLog.AGGREGATION_DB_LOG);

		setValue(0, revisionId);
		setValue(1, log);
		setValue(2, partition);
		setValue(3, file);
		setValue(4, fileIndex);
		setValue(5, position);
	}
}
