/*
 * Copyright (C) 2015 SoftIndex LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This class is generated by jOOQ
 */
package io.datakernel.cube.sql.tables;

import io.datakernel.cube.sql.DefaultSchema;
import io.datakernel.cube.sql.Keys;
import io.datakernel.cube.sql.tables.records.AggregationRevisionRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.6.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AggregationRevision extends TableImpl<AggregationRevisionRecord> {

	private static final long serialVersionUID = 555480314;

	/**
	 * The reference instance of <code>aggregation_revision</code>
	 */
	public static final AggregationRevision AGGREGATION_REVISION = new AggregationRevision();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AggregationRevisionRecord> getRecordType() {
		return AggregationRevisionRecord.class;
	}

	/**
	 * The column <code>aggregation_revision.id</code>.
	 */
	public final TableField<AggregationRevisionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>aggregation_revision</code> table reference
	 */
	public AggregationRevision() {
		this("aggregation_revision", null);
	}

	/**
	 * Create an aliased <code>aggregation_revision</code> table reference
	 */
	public AggregationRevision(String alias) {
		this(alias, AGGREGATION_REVISION);
	}

	private AggregationRevision(String alias, Table<AggregationRevisionRecord> aliased) {
		this(alias, aliased, null);
	}

	private AggregationRevision(String alias, Table<AggregationRevisionRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AggregationRevisionRecord, Integer> getIdentity() {
		return Keys.IDENTITY_AGGREGATION_REVISION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AggregationRevisionRecord> getPrimaryKey() {
		return Keys.KEY_AGGREGATION_REVISION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AggregationRevisionRecord>> getKeys() {
		return Arrays.<UniqueKey<AggregationRevisionRecord>>asList(Keys.KEY_AGGREGATION_REVISION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationRevision as(String alias) {
		return new AggregationRevision(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AggregationRevision rename(String name) {
		return new AggregationRevision(name, null);
	}
}
