/*
 * Copyright (C) 2015 SoftIndex LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This class is generated by jOOQ
 */
package io.datakernel.aggregation_db.sql.tables.records;


import io.datakernel.aggregation_db.sql.tables.AggregationDbChunk;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregationDbChunkRecord extends UpdatableRecordImpl<AggregationDbChunkRecord> {

	private static final long serialVersionUID = -742775134;

	/**
	 * Setter for <code>aggregation_db_chunk.id</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.id</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.created</code>.
	 */
	public void setCreated(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.created</code>.
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.aggregation_id</code>.
	 */
	public void setAggregationId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.aggregation_id</code>.
	 */
	public String getAggregationId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.revision_id</code>.
	 */
	public void setRevisionId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.revision_id</code>.
	 */
	public Integer getRevisionId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.min_revision_id</code>.
	 */
	public void setMinRevisionId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.min_revision_id</code>.
	 */
	public Integer getMinRevisionId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.max_revision_id</code>.
	 */
	public void setMaxRevisionId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.max_revision_id</code>.
	 */
	public Integer getMaxRevisionId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.count</code>.
	 */
	public void setCount(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.count</code>.
	 */
	public Integer getCount() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.consolidated_revision_id</code>.
	 */
	public void setConsolidatedRevisionId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.consolidated_revision_id</code>.
	 */
	public Integer getConsolidatedRevisionId() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.consolidation_started</code>.
	 */
	public void setConsolidationStarted(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.consolidation_started</code>.
	 */
	public Timestamp getConsolidationStarted() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.consolidation_completed</code>.
	 */
	public void setConsolidationCompleted(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.consolidation_completed</code>.
	 */
	public Timestamp getConsolidationCompleted() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.keys</code>.
	 */
	public void setKeys(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.keys</code>.
	 */
	public String getKeys() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.fields</code>.
	 */
	public void setFields(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.fields</code>.
	 */
	public String getFields() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d1_min</code>.
	 */
	public void setD1Min(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d1_min</code>.
	 */
	public String getD1Min() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d1_max</code>.
	 */
	public void setD1Max(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d1_max</code>.
	 */
	public String getD1Max() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d2_min</code>.
	 */
	public void setD2Min(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d2_min</code>.
	 */
	public String getD2Min() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d2_max</code>.
	 */
	public void setD2Max(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d2_max</code>.
	 */
	public String getD2Max() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d3_min</code>.
	 */
	public void setD3Min(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d3_min</code>.
	 */
	public String getD3Min() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d3_max</code>.
	 */
	public void setD3Max(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d3_max</code>.
	 */
	public String getD3Max() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d4_min</code>.
	 */
	public void setD4Min(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d4_min</code>.
	 */
	public String getD4Min() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d4_max</code>.
	 */
	public void setD4Max(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d4_max</code>.
	 */
	public String getD4Max() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d5_min</code>.
	 */
	public void setD5Min(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d5_min</code>.
	 */
	public String getD5Min() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d5_max</code>.
	 */
	public void setD5Max(String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d5_max</code>.
	 */
	public String getD5Max() {
		return (String) getValue(21);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d6_min</code>.
	 */
	public void setD6Min(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d6_min</code>.
	 */
	public String getD6Min() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d6_max</code>.
	 */
	public void setD6Max(String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d6_max</code>.
	 */
	public String getD6Max() {
		return (String) getValue(23);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d7_min</code>.
	 */
	public void setD7Min(String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d7_min</code>.
	 */
	public String getD7Min() {
		return (String) getValue(24);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d7_max</code>.
	 */
	public void setD7Max(String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d7_max</code>.
	 */
	public String getD7Max() {
		return (String) getValue(25);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d8_min</code>.
	 */
	public void setD8Min(String value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d8_min</code>.
	 */
	public String getD8Min() {
		return (String) getValue(26);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d8_max</code>.
	 */
	public void setD8Max(String value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d8_max</code>.
	 */
	public String getD8Max() {
		return (String) getValue(27);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d9_min</code>.
	 */
	public void setD9Min(String value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d9_min</code>.
	 */
	public String getD9Min() {
		return (String) getValue(28);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d9_max</code>.
	 */
	public void setD9Max(String value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d9_max</code>.
	 */
	public String getD9Max() {
		return (String) getValue(29);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d10_min</code>.
	 */
	public void setD10Min(String value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d10_min</code>.
	 */
	public String getD10Min() {
		return (String) getValue(30);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d10_max</code>.
	 */
	public void setD10Max(String value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d10_max</code>.
	 */
	public String getD10Max() {
		return (String) getValue(31);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d11_min</code>.
	 */
	public void setD11Min(String value) {
		setValue(32, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d11_min</code>.
	 */
	public String getD11Min() {
		return (String) getValue(32);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d11_max</code>.
	 */
	public void setD11Max(String value) {
		setValue(33, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d11_max</code>.
	 */
	public String getD11Max() {
		return (String) getValue(33);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d12_min</code>.
	 */
	public void setD12Min(String value) {
		setValue(34, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d12_min</code>.
	 */
	public String getD12Min() {
		return (String) getValue(34);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d12_max</code>.
	 */
	public void setD12Max(String value) {
		setValue(35, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d12_max</code>.
	 */
	public String getD12Max() {
		return (String) getValue(35);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d13_min</code>.
	 */
	public void setD13Min(String value) {
		setValue(36, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d13_min</code>.
	 */
	public String getD13Min() {
		return (String) getValue(36);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d13_max</code>.
	 */
	public void setD13Max(String value) {
		setValue(37, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d13_max</code>.
	 */
	public String getD13Max() {
		return (String) getValue(37);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d14_min</code>.
	 */
	public void setD14Min(String value) {
		setValue(38, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d14_min</code>.
	 */
	public String getD14Min() {
		return (String) getValue(38);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d14_max</code>.
	 */
	public void setD14Max(String value) {
		setValue(39, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d14_max</code>.
	 */
	public String getD14Max() {
		return (String) getValue(39);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d15_min</code>.
	 */
	public void setD15Min(String value) {
		setValue(40, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d15_min</code>.
	 */
	public String getD15Min() {
		return (String) getValue(40);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d15_max</code>.
	 */
	public void setD15Max(String value) {
		setValue(41, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d15_max</code>.
	 */
	public String getD15Max() {
		return (String) getValue(41);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d16_min</code>.
	 */
	public void setD16Min(String value) {
		setValue(42, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d16_min</code>.
	 */
	public String getD16Min() {
		return (String) getValue(42);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d16_max</code>.
	 */
	public void setD16Max(String value) {
		setValue(43, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d16_max</code>.
	 */
	public String getD16Max() {
		return (String) getValue(43);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d17_min</code>.
	 */
	public void setD17Min(String value) {
		setValue(44, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d17_min</code>.
	 */
	public String getD17Min() {
		return (String) getValue(44);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d17_max</code>.
	 */
	public void setD17Max(String value) {
		setValue(45, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d17_max</code>.
	 */
	public String getD17Max() {
		return (String) getValue(45);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d18_min</code>.
	 */
	public void setD18Min(String value) {
		setValue(46, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d18_min</code>.
	 */
	public String getD18Min() {
		return (String) getValue(46);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d18_max</code>.
	 */
	public void setD18Max(String value) {
		setValue(47, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d18_max</code>.
	 */
	public String getD18Max() {
		return (String) getValue(47);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d19_min</code>.
	 */
	public void setD19Min(String value) {
		setValue(48, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d19_min</code>.
	 */
	public String getD19Min() {
		return (String) getValue(48);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d19_max</code>.
	 */
	public void setD19Max(String value) {
		setValue(49, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d19_max</code>.
	 */
	public String getD19Max() {
		return (String) getValue(49);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d20_min</code>.
	 */
	public void setD20Min(String value) {
		setValue(50, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d20_min</code>.
	 */
	public String getD20Min() {
		return (String) getValue(50);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d20_max</code>.
	 */
	public void setD20Max(String value) {
		setValue(51, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d20_max</code>.
	 */
	public String getD20Max() {
		return (String) getValue(51);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d21_min</code>.
	 */
	public void setD21Min(String value) {
		setValue(52, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d21_min</code>.
	 */
	public String getD21Min() {
		return (String) getValue(52);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d21_max</code>.
	 */
	public void setD21Max(String value) {
		setValue(53, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d21_max</code>.
	 */
	public String getD21Max() {
		return (String) getValue(53);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d22_min</code>.
	 */
	public void setD22Min(String value) {
		setValue(54, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d22_min</code>.
	 */
	public String getD22Min() {
		return (String) getValue(54);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d22_max</code>.
	 */
	public void setD22Max(String value) {
		setValue(55, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d22_max</code>.
	 */
	public String getD22Max() {
		return (String) getValue(55);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d23_min</code>.
	 */
	public void setD23Min(String value) {
		setValue(56, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d23_min</code>.
	 */
	public String getD23Min() {
		return (String) getValue(56);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d23_max</code>.
	 */
	public void setD23Max(String value) {
		setValue(57, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d23_max</code>.
	 */
	public String getD23Max() {
		return (String) getValue(57);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d24_min</code>.
	 */
	public void setD24Min(String value) {
		setValue(58, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d24_min</code>.
	 */
	public String getD24Min() {
		return (String) getValue(58);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d24_max</code>.
	 */
	public void setD24Max(String value) {
		setValue(59, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d24_max</code>.
	 */
	public String getD24Max() {
		return (String) getValue(59);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d25_min</code>.
	 */
	public void setD25Min(String value) {
		setValue(60, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d25_min</code>.
	 */
	public String getD25Min() {
		return (String) getValue(60);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d25_max</code>.
	 */
	public void setD25Max(String value) {
		setValue(61, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d25_max</code>.
	 */
	public String getD25Max() {
		return (String) getValue(61);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d26_min</code>.
	 */
	public void setD26Min(String value) {
		setValue(62, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d26_min</code>.
	 */
	public String getD26Min() {
		return (String) getValue(62);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d26_max</code>.
	 */
	public void setD26Max(String value) {
		setValue(63, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d26_max</code>.
	 */
	public String getD26Max() {
		return (String) getValue(63);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d27_min</code>.
	 */
	public void setD27Min(String value) {
		setValue(64, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d27_min</code>.
	 */
	public String getD27Min() {
		return (String) getValue(64);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d27_max</code>.
	 */
	public void setD27Max(String value) {
		setValue(65, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d27_max</code>.
	 */
	public String getD27Max() {
		return (String) getValue(65);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d28_min</code>.
	 */
	public void setD28Min(String value) {
		setValue(66, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d28_min</code>.
	 */
	public String getD28Min() {
		return (String) getValue(66);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d28_max</code>.
	 */
	public void setD28Max(String value) {
		setValue(67, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d28_max</code>.
	 */
	public String getD28Max() {
		return (String) getValue(67);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d29_min</code>.
	 */
	public void setD29Min(String value) {
		setValue(68, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d29_min</code>.
	 */
	public String getD29Min() {
		return (String) getValue(68);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d29_max</code>.
	 */
	public void setD29Max(String value) {
		setValue(69, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d29_max</code>.
	 */
	public String getD29Max() {
		return (String) getValue(69);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d30_min</code>.
	 */
	public void setD30Min(String value) {
		setValue(70, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d30_min</code>.
	 */
	public String getD30Min() {
		return (String) getValue(70);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d30_max</code>.
	 */
	public void setD30Max(String value) {
		setValue(71, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d30_max</code>.
	 */
	public String getD30Max() {
		return (String) getValue(71);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d31_min</code>.
	 */
	public void setD31Min(String value) {
		setValue(72, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d31_min</code>.
	 */
	public String getD31Min() {
		return (String) getValue(72);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d31_max</code>.
	 */
	public void setD31Max(String value) {
		setValue(73, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d31_max</code>.
	 */
	public String getD31Max() {
		return (String) getValue(73);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d32_min</code>.
	 */
	public void setD32Min(String value) {
		setValue(74, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d32_min</code>.
	 */
	public String getD32Min() {
		return (String) getValue(74);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d32_max</code>.
	 */
	public void setD32Max(String value) {
		setValue(75, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d32_max</code>.
	 */
	public String getD32Max() {
		return (String) getValue(75);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d33_min</code>.
	 */
	public void setD33Min(String value) {
		setValue(76, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d33_min</code>.
	 */
	public String getD33Min() {
		return (String) getValue(76);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d33_max</code>.
	 */
	public void setD33Max(String value) {
		setValue(77, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d33_max</code>.
	 */
	public String getD33Max() {
		return (String) getValue(77);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d34_min</code>.
	 */
	public void setD34Min(String value) {
		setValue(78, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d34_min</code>.
	 */
	public String getD34Min() {
		return (String) getValue(78);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d34_max</code>.
	 */
	public void setD34Max(String value) {
		setValue(79, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d34_max</code>.
	 */
	public String getD34Max() {
		return (String) getValue(79);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d35_min</code>.
	 */
	public void setD35Min(String value) {
		setValue(80, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d35_min</code>.
	 */
	public String getD35Min() {
		return (String) getValue(80);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d35_max</code>.
	 */
	public void setD35Max(String value) {
		setValue(81, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d35_max</code>.
	 */
	public String getD35Max() {
		return (String) getValue(81);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d36_min</code>.
	 */
	public void setD36Min(String value) {
		setValue(82, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d36_min</code>.
	 */
	public String getD36Min() {
		return (String) getValue(82);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d36_max</code>.
	 */
	public void setD36Max(String value) {
		setValue(83, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d36_max</code>.
	 */
	public String getD36Max() {
		return (String) getValue(83);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d37_min</code>.
	 */
	public void setD37Min(String value) {
		setValue(84, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d37_min</code>.
	 */
	public String getD37Min() {
		return (String) getValue(84);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d37_max</code>.
	 */
	public void setD37Max(String value) {
		setValue(85, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d37_max</code>.
	 */
	public String getD37Max() {
		return (String) getValue(85);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d38_min</code>.
	 */
	public void setD38Min(String value) {
		setValue(86, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d38_min</code>.
	 */
	public String getD38Min() {
		return (String) getValue(86);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d38_max</code>.
	 */
	public void setD38Max(String value) {
		setValue(87, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d38_max</code>.
	 */
	public String getD38Max() {
		return (String) getValue(87);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d39_min</code>.
	 */
	public void setD39Min(String value) {
		setValue(88, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d39_min</code>.
	 */
	public String getD39Min() {
		return (String) getValue(88);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d39_max</code>.
	 */
	public void setD39Max(String value) {
		setValue(89, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d39_max</code>.
	 */
	public String getD39Max() {
		return (String) getValue(89);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d40_min</code>.
	 */
	public void setD40Min(String value) {
		setValue(90, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d40_min</code>.
	 */
	public String getD40Min() {
		return (String) getValue(90);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d40_max</code>.
	 */
	public void setD40Max(String value) {
		setValue(91, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d40_max</code>.
	 */
	public String getD40Max() {
		return (String) getValue(91);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AggregationDbChunkRecord
	 */
	public AggregationDbChunkRecord() {
		super(AggregationDbChunk.AGGREGATION_DB_CHUNK);
	}

	/**
	 * Create a detached, initialised AggregationDbChunkRecord
	 */
	public AggregationDbChunkRecord(Long id, Timestamp created, String aggregationId, Integer revisionId, Integer minRevisionId, Integer maxRevisionId, Integer count, Integer consolidatedRevisionId, Timestamp consolidationStarted, Timestamp consolidationCompleted, String keys, String fields, String d1Min, String d1Max, String d2Min, String d2Max, String d3Min, String d3Max, String d4Min, String d4Max, String d5Min, String d5Max, String d6Min, String d6Max, String d7Min, String d7Max, String d8Min, String d8Max, String d9Min, String d9Max, String d10Min, String d10Max, String d11Min, String d11Max, String d12Min, String d12Max, String d13Min, String d13Max, String d14Min, String d14Max, String d15Min, String d15Max, String d16Min, String d16Max, String d17Min, String d17Max, String d18Min, String d18Max, String d19Min, String d19Max, String d20Min, String d20Max, String d21Min, String d21Max, String d22Min, String d22Max, String d23Min, String d23Max, String d24Min, String d24Max, String d25Min, String d25Max, String d26Min, String d26Max, String d27Min, String d27Max, String d28Min, String d28Max, String d29Min, String d29Max, String d30Min, String d30Max, String d31Min, String d31Max, String d32Min, String d32Max, String d33Min, String d33Max, String d34Min, String d34Max, String d35Min, String d35Max, String d36Min, String d36Max, String d37Min, String d37Max, String d38Min, String d38Max, String d39Min, String d39Max, String d40Min, String d40Max) {
		super(AggregationDbChunk.AGGREGATION_DB_CHUNK);

		setValue(0, id);
		setValue(1, created);
		setValue(2, aggregationId);
		setValue(3, revisionId);
		setValue(4, minRevisionId);
		setValue(5, maxRevisionId);
		setValue(6, count);
		setValue(7, consolidatedRevisionId);
		setValue(8, consolidationStarted);
		setValue(9, consolidationCompleted);
		setValue(10, keys);
		setValue(11, fields);
		setValue(12, d1Min);
		setValue(13, d1Max);
		setValue(14, d2Min);
		setValue(15, d2Max);
		setValue(16, d3Min);
		setValue(17, d3Max);
		setValue(18, d4Min);
		setValue(19, d4Max);
		setValue(20, d5Min);
		setValue(21, d5Max);
		setValue(22, d6Min);
		setValue(23, d6Max);
		setValue(24, d7Min);
		setValue(25, d7Max);
		setValue(26, d8Min);
		setValue(27, d8Max);
		setValue(28, d9Min);
		setValue(29, d9Max);
		setValue(30, d10Min);
		setValue(31, d10Max);
		setValue(32, d11Min);
		setValue(33, d11Max);
		setValue(34, d12Min);
		setValue(35, d12Max);
		setValue(36, d13Min);
		setValue(37, d13Max);
		setValue(38, d14Min);
		setValue(39, d14Max);
		setValue(40, d15Min);
		setValue(41, d15Max);
		setValue(42, d16Min);
		setValue(43, d16Max);
		setValue(44, d17Min);
		setValue(45, d17Max);
		setValue(46, d18Min);
		setValue(47, d18Max);
		setValue(48, d19Min);
		setValue(49, d19Max);
		setValue(50, d20Min);
		setValue(51, d20Max);
		setValue(52, d21Min);
		setValue(53, d21Max);
		setValue(54, d22Min);
		setValue(55, d22Max);
		setValue(56, d23Min);
		setValue(57, d23Max);
		setValue(58, d24Min);
		setValue(59, d24Max);
		setValue(60, d25Min);
		setValue(61, d25Max);
		setValue(62, d26Min);
		setValue(63, d26Max);
		setValue(64, d27Min);
		setValue(65, d27Max);
		setValue(66, d28Min);
		setValue(67, d28Max);
		setValue(68, d29Min);
		setValue(69, d29Max);
		setValue(70, d30Min);
		setValue(71, d30Max);
		setValue(72, d31Min);
		setValue(73, d31Max);
		setValue(74, d32Min);
		setValue(75, d32Max);
		setValue(76, d33Min);
		setValue(77, d33Max);
		setValue(78, d34Min);
		setValue(79, d34Max);
		setValue(80, d35Min);
		setValue(81, d35Max);
		setValue(82, d36Min);
		setValue(83, d36Max);
		setValue(84, d37Min);
		setValue(85, d37Max);
		setValue(86, d38Min);
		setValue(87, d38Max);
		setValue(88, d39Min);
		setValue(89, d39Max);
		setValue(90, d40Min);
		setValue(91, d40Max);
	}
}
