/**
 * This class is generated by jOOQ
 */
package io.datakernel.aggregation.sql.tables.records;

import io.datakernel.aggregation.sql.tables.AggregationDbRevision;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregationDbRevisionRecord extends UpdatableRecordImpl<AggregationDbRevisionRecord> implements Record1<Integer> {

	private static final long serialVersionUID = -234261682;

	/**
	 * Setter for <code>aggregation_db_revision.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>aggregation_db_revision.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Integer> fieldsRow() {
		return (Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Integer> valuesRow() {
		return (Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AggregationDbRevision.AGGREGATION_DB_REVISION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbRevisionRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AggregationDbRevisionRecord values(Integer value1) {
		value1(value1);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AggregationDbRevisionRecord
	 */
	public AggregationDbRevisionRecord() {
		super(AggregationDbRevision.AGGREGATION_DB_REVISION);
	}

	/**
	 * Create a detached, initialised AggregationDbRevisionRecord
	 */
	public AggregationDbRevisionRecord(Integer id) {
		super(AggregationDbRevision.AGGREGATION_DB_REVISION);

		setValue(0, id);
	}
}
