/**
 * This class is generated by jOOQ
 */
package io.datakernel.aggregation.sql.tables.records;

import io.datakernel.aggregation.sql.tables.AggregationDbChunk;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregationDbChunkRecord extends UpdatableRecordImpl<AggregationDbChunkRecord> {

	private static final long serialVersionUID = -1914951509;

	/**
	 * Setter for <code>aggregation_db_chunk.id</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.id</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.created</code>.
	 */
	public void setCreated(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.created</code>.
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.aggregation_id</code>.
	 */
	public void setAggregationId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.aggregation_id</code>.
	 */
	public String getAggregationId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.revision_id</code>.
	 */
	public void setRevisionId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.revision_id</code>.
	 */
	public Integer getRevisionId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.count</code>.
	 */
	public void setCount(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.count</code>.
	 */
	public Integer getCount() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.consolidated_revision_id</code>.
	 */
	public void setConsolidatedRevisionId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.consolidated_revision_id</code>.
	 */
	public Integer getConsolidatedRevisionId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.consolidation_started</code>.
	 */
	public void setConsolidationStarted(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.consolidation_started</code>.
	 */
	public Timestamp getConsolidationStarted() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.consolidation_completed</code>.
	 */
	public void setConsolidationCompleted(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.consolidation_completed</code>.
	 */
	public Timestamp getConsolidationCompleted() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.process_id</code>.
	 */
	public void setProcessId(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.process_id</code>.
	 */
	public String getProcessId() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.keys</code>.
	 */
	public void setKeys(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.keys</code>.
	 */
	public String getKeys() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.fields</code>.
	 */
	public void setFields(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.fields</code>.
	 */
	public String getFields() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d1_min</code>.
	 */
	public void setD1Min(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d1_min</code>.
	 */
	public String getD1Min() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d1_max</code>.
	 */
	public void setD1Max(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d1_max</code>.
	 */
	public String getD1Max() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d2_min</code>.
	 */
	public void setD2Min(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d2_min</code>.
	 */
	public String getD2Min() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d2_max</code>.
	 */
	public void setD2Max(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d2_max</code>.
	 */
	public String getD2Max() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d3_min</code>.
	 */
	public void setD3Min(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d3_min</code>.
	 */
	public String getD3Min() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d3_max</code>.
	 */
	public void setD3Max(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d3_max</code>.
	 */
	public String getD3Max() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d4_min</code>.
	 */
	public void setD4Min(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d4_min</code>.
	 */
	public String getD4Min() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d4_max</code>.
	 */
	public void setD4Max(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d4_max</code>.
	 */
	public String getD4Max() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d5_min</code>.
	 */
	public void setD5Min(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d5_min</code>.
	 */
	public String getD5Min() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d5_max</code>.
	 */
	public void setD5Max(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d5_max</code>.
	 */
	public String getD5Max() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d6_min</code>.
	 */
	public void setD6Min(String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d6_min</code>.
	 */
	public String getD6Min() {
		return (String) getValue(21);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d6_max</code>.
	 */
	public void setD6Max(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d6_max</code>.
	 */
	public String getD6Max() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d7_min</code>.
	 */
	public void setD7Min(String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d7_min</code>.
	 */
	public String getD7Min() {
		return (String) getValue(23);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d7_max</code>.
	 */
	public void setD7Max(String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d7_max</code>.
	 */
	public String getD7Max() {
		return (String) getValue(24);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d8_min</code>.
	 */
	public void setD8Min(String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d8_min</code>.
	 */
	public String getD8Min() {
		return (String) getValue(25);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d8_max</code>.
	 */
	public void setD8Max(String value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d8_max</code>.
	 */
	public String getD8Max() {
		return (String) getValue(26);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d9_min</code>.
	 */
	public void setD9Min(String value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d9_min</code>.
	 */
	public String getD9Min() {
		return (String) getValue(27);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d9_max</code>.
	 */
	public void setD9Max(String value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d9_max</code>.
	 */
	public String getD9Max() {
		return (String) getValue(28);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d10_min</code>.
	 */
	public void setD10Min(String value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d10_min</code>.
	 */
	public String getD10Min() {
		return (String) getValue(29);
	}

	/**
	 * Setter for <code>aggregation_db_chunk.d10_max</code>.
	 */
	public void setD10Max(String value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>aggregation_db_chunk.d10_max</code>.
	 */
	public String getD10Max() {
		return (String) getValue(30);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AggregationDbChunkRecord
	 */
	public AggregationDbChunkRecord() {
		super(AggregationDbChunk.AGGREGATION_DB_CHUNK);
	}

	/**
	 * Create a detached, initialised AggregationDbChunkRecord
	 */
	public AggregationDbChunkRecord(Long id, Timestamp created, String aggregationId, Integer revisionId, Integer count, Integer consolidatedRevisionId, Timestamp consolidationStarted, Timestamp consolidationCompleted, String processId, String keys, String fields, String d1Min, String d1Max, String d2Min, String d2Max, String d3Min, String d3Max, String d4Min, String d4Max, String d5Min, String d5Max, String d6Min, String d6Max, String d7Min, String d7Max, String d8Min, String d8Max, String d9Min, String d9Max, String d10Min, String d10Max) {
		super(AggregationDbChunk.AGGREGATION_DB_CHUNK);

		setValue(0, id);
		setValue(1, created);
		setValue(2, aggregationId);
		setValue(3, revisionId);
		setValue(4, count);
		setValue(5, consolidatedRevisionId);
		setValue(6, consolidationStarted);
		setValue(7, consolidationCompleted);
		setValue(8, processId);
		setValue(9, keys);
		setValue(10, fields);
		setValue(11, d1Min);
		setValue(12, d1Max);
		setValue(13, d2Min);
		setValue(14, d2Max);
		setValue(15, d3Min);
		setValue(16, d3Max);
		setValue(17, d4Min);
		setValue(18, d4Max);
		setValue(19, d5Min);
		setValue(20, d5Max);
		setValue(21, d6Min);
		setValue(22, d6Max);
		setValue(23, d7Min);
		setValue(24, d7Max);
		setValue(25, d8Min);
		setValue(26, d8Max);
		setValue(27, d9Min);
		setValue(28, d9Max);
		setValue(29, d10Min);
		setValue(30, d10Max);
	}
}
